//Now a nice little list of all the languages.... (It took forever for me to get this)
let languages = {
    en: "English (United States)",
    fr: "French (France)",
    de: "German (Germany)",
    it: "Italian (Italy)",
    nl: "Dutch (Netherlands)",
    sv: "Swedish (Sweden)",
    es: "Spanish (Spain)",
    da: "Danish (Denmark)",
    pt: "Portuguese (Brazil)",
    no: "Norwegian Bokmål (Norway)",
    nn: "Norwegian Nynorsk (Norway)",
    he: "Hebrew (Israel)",
    ja: "Japanese (Japan)",
    fi: "Finnish (Finland)",
    el: "Greek (Greece)",
    is: "Icelandic (Iceland)",
    mt: "Maltese (Malta)",
    tr: "Turkish (Turkey)",
    hr: "Croatian (Croatia)",
    "zh-Hans": "Chinese (China)",
    ur: "Urdu (Pakistan)",
    hi: "Hindi (India)",
    th: "Thai (Thailand)",
    ko: "Korean (South Korea)",
    lt: "Lithuanian (Lithuania)",
    pl: "Polish (Poland)",
    hu: "Hungarian (Hungary)",
    et: "Estonian (Estonia)",
    lv: "Latvian (Latvia)",
    fo: "Faroese (Faroe Islands)",
    fa: "Persian (Iran)",
    ru: "Russian (Russia)",
    ga: "Irish (Ireland)",
    ro: "Romanian (Romania)",
    cs: "Czech (Czech Republic)",
    sk: "Slovak (Slovakia)",
    sl: "Slovenian (Slovenia)",
    sr: "Serbian (Serbia)",
    mk: "Macedonian (Macedonia)",
    bg: "Bulgarian (Bulgaria)",
    uk: "Ukrainian (Ukraine)",
    be: "Belarusian (Belarus)",
    uz: "Uzbek (Uzbekistan)",
    hy: "Armenian (Armenia)",
    ka: "Georgian (Georgia)",
    en_US: "English (United States)",
    fr_FR: "French (France)",
    de_DE: "German (Germany)",
    it_IT: "Italian (Italy)",
    nl_NL: "Dutch (Netherlands)",
    sv_SE: "Swedish (Sweden)",
    es_ES: "Spanish (Spain)",
    da_DK: "Danish (Denmark)",
    pt_BR: "Portuguese (Brazil)",
    nb_NO: "Norwegian Bokmål (Norway)",
    nb: "Norwegian Bokmål (Norway)",
    nn_NO: "Norwegian Nynorsk (Norway)",
    he_IL: "Hebrew (Israel)",
    ja_JP: "Japanese (Japan)",
    fi_FI: "Finnish (Finland)",
    el_GR: "Greek (Greece)",
    is_IS: "Icelandic (Iceland)",
    mt_MT: "Maltese (Malta)",
    tr_TR: "Turkish (Turkey)",
    hr_HR: "Croatian (Croatia)",
    zh: "Chinese (China)",
    zh_CN: "Chinese (China)",
    ur_PK: "Urdu (Pakistan)",
    hi_IN: "Hindi (India)",
    th_TH: "Thai (Thailand)",
    ko_KR: "Korean (South Korea)",
    lt_LT: "Lithuanian (Lithuania)",
    pl_PL: "Polish (Poland)",
    hu_HU: "Hungarian (Hungary)",
    et_EE: "Estonian (Estonia)",
    lv_LV: "Latvian (Latvia)",
    fo_FO: "Faroese (Faroe Islands)",
    fa_IR: "Persian (Iran)",
    ru_RU: "Russian (Russia)",
    ga_IE: "Irish (Ireland)",
    ro_RO: "Romanian (Romania)",
    cs_CZ: "Czech (Czech Republic)",
    sk_SK: "Slovak (Slovakia)",
    sl_SI: "Slovenian (Slovenia)",
    sr_CS: "Serbian (Serbia)",
    mk_MK: "Macedonian (Macedonia)",
    bg_BG: "Bulgarian (Bulgaria)",
    uk_UA: "Ukrainian (Ukraine)",
    be_BY: "Belarusian (Belarus)",
    uz_UZ: "Uzbek (Uzbekistan)",
    hy_AM: "Armenian (Armenia)",
    ka_GE: "Georgian (Georgia)",
    en_GB: "English (United Kingdom)",
    en_AU: "English (Australia)",
    en_CA: "English (Canada)",
    en_SG: "English (Singapore)",
    en_IE: "English (Ireland)",
    it_CH: "Italian (Switzerland)",
    de_CH: "German (Switzerland)",
    de_AT: "German (Austria)",
    nl_BE: "Dutch (Belgium)",
    zh_TW: "Chinese (Taiwan)",
    fr_CA: "French (Canada)",
    fr_CH: "French (Switzerland)",
    fr_BE: "French (Belgium)",
    pt_PT: "Portuguese (Portugal)",
    ar: "Arabic",
    el_CY: "Greek (Cyprus)",
    ur_IN: "Urdu (India)",
    se: "Northern Sami",
    yi: "Yiddish",
    kk: "Kazakh",
    sq: "Albanian",
    mo: "Moldavian",
    ky: "Kyrgyz",
    tg: "Tajik",
    tk: "Turkmen",
    mn: "Mongolian",
    ps: "Pashto",
    ku: "Kurdish",
    ks: "Kashmiri",
    sd: "Sindhi",
    bo: "Tibetan",
    es_XL: "Spanish (Latin America)",
    ne_NP: "Nepali (Nepal)",
    ne: "Nepali (Nepal)",
    sa: "Sanskrit",
    mr: "Marathi (India)",
    mr_IN: "Marathi (India)",
    bn: "Bengali",
    as: "Assamese",
    gu_IN: "Gujarati (India)",
    gu: "Gujarati (India)",
    pa: "Punjabi",
    or: "Oriya",
    ml: "Malayalam",
    kn: "Kannada",
    ta: "Tamil",
    te: "Telugu",
    si: "Sinhala",
    my: "Burmese",
    km: "Khmer",
    lo: "Lao",
    vi_VN: "Vietnamese (Vietnam)",
    vi: "Vietnamese (Vietnam)",
    id: "Indonesian",
    tl: "Tagalog",
    ms: "Malay",
    am: "Amharic",
    ti: "Tigrinya",
    om: "Oromo",
    so: "Somali",
    sw: "Swahili",
    rw: "Kinyarwanda",
    rn: "Rundi",
    ny: "Nyanja",
    mg: "Malagasy",
    eo: "Esperanto",
    cy: "Welsh",
    eu: "Basque",
    ca_ES: "Catalan (Spain)",
    ca: "Catalan (Spain)",
    la: "Latin",
    qu: "Quechua",
    gn: "Guarani",
    ay: "Aymara",
    tt: "Tatar",
    ug: "Uyghur",
    dz_BT: "Dzongkha (Bhutan)",
    dz: "Dzongkha (Bhutan)",
    jv: "Javanese",
    su: "Sundanese",
    gl: "Galician",
    af_ZA: "Afrikaans (South Africa)",
    af: "Afrikaans (South Africa)",
    br: "Breton",
    iu_CA: "Inuktitut (Canada)",
    iu: "Inuktitut (Canada)",
    gd: "Scottish Gaelic",
    gv: "Manx",
    to_TO: "Tongan (Tonga)",
    to: "Tongan (Tonga)",
    grc: "Ancient Greek",
    kl: "Kalaallisut",
    az: "Azerbaijani"
};

module.exports = {
    languages
}
