//Now a nice little list of all the languages.... (It took forever for me to get this)

//The list below this one is more accurate, but MUCH more cluttered.

let langugaes = languages = {
  en: "English",
  fr: "French",
  de: "German",
  it: "Italian",
  nl: "Dutch",
  sv: "Swedish",
  es: "Spanish",
  da: "Danish",
  pt: "Portuguese",
  no: "Norwegian Bokmål",
  nn: "Norwegian Nynorsk",
  he: "Hebrew",
  ja: "Japanese",
  fi: "Finnish",
  el: "Greek",
  is: "Icelandic",
  mt: "Maltese",
  tr: "Turkish",
  hr: "Croatian",
  "zh-Hans": "Chinese",
  ur: "Urdu",
  hi: "Hindi",
  th: "Thai",
  ko: "Korean",
  lt: "Lithuanian",
  pl: "Polish",
  hu: "Hungarian",
  et: "Estonian",
  lv: "Latvian",
  fo: "Faroese",
  fa: "Persian",
  ru: "Russian",
  ga: "Irish",
  ro: "Romanian",
  cs: "Czech",
  sk: "Slovak",
  sl: "Slovenian",
  sr: "Serbian",
  mk: "Macedonian",
  bg: "Bulgarian",
  uk: "Ukrainian",
  be: "Belarusian",
  uz: "Uzbek",
  hy: "Armenian",
  ka: "Georgian",
  en_US: "English",
  fr_FR: "French",
  de_DE: "German",
  it_IT: "Italian",
  nl_NL: "Dutch",
  sv_SE: "Swedish",
  es_ES: "Spanish",
  da_DK: "Danish",
  pt_BR: "Portuguese",
  nb_NO: "Norwegian Bokmål",
  nb: "Norwegian Bokmål",
  nn_NO: "Norwegian Nynorsk",
  he_IL: "Hebrew",
  ja_JP: "Japanese",
  fi_FI: "Finnish",
  el_GR: "Greek",
  is_IS: "Icelandic",
  mt_MT: "Maltese",
  tr_TR: "Turkish",
  hr_HR: "Croatian",
  zh: "Chinese",
  zh_CN: "Chinese",
  ur_PK: "Urdu",
  hi_IN: "Hindi",
  th_TH: "Thai",
  ko_KR: "Korean",
  lt_LT: "Lithuanian",
  pl_PL: "Polish",
  hu_HU: "Hungarian",
  et_EE: "Estonian",
  lv_LV: "Latvian",
  fo_FO: "Faroese",
  fa_IR: "Persian",
  ru_RU: "Russian",
  ga_IE: "Irish",
  ro_RO: "Romanian",
  cs_CZ: "Czech",
  sk_SK: "Slovak",
  sl_SI: "Slovenian",
  sr_CS: "Serbian",
  mk_MK: "Macedonian",
  bg_BG: "Bulgarian",
  uk_UA: "Ukrainian",
  be_BY: "Belarusian",
  uz_UZ: "Uzbek",
  hy_AM: "Armenian",
  ka_GE: "Georgian",
  en_GB: "English",
  en_AU: "English",
  en_CA: "English",
  en_SG: "English",
  en_IE: "English",
  it_CH: "Italian",
  de_CH: "German",
  de_AT: "German",
  nl_BE: "Dutch",
  zh_TW: "Chinese",
  fr_CA: "French",
  fr_CH: "French",
  fr_BE: "French",
  pt_PT: "Portuguese",
  ar: "Arabic",
  el_CY: "Greek",
  ur_IN: "Urdu",
  se: "Northern Sami",
  yi: "Yiddish",
  kk: "Kazakh",
  sq: "Albanian",
  mo: "Moldavian",
  ky: "Kyrgyz",
  tg: "Tajik",
  tk: "Turkmen",
  mn: "Mongolian",
  ps: "Pashto",
  ku: "Kurdish",
  ks: "Kashmiri",
  sd: "Sindhi",
  bo: "Tibetan",
  es_XL: "Spanish",
  ne_NP: "Nepali",
  ne: "Nepali",
  sa: "Sanskrit",
  mr: "Marathi",
  mr_IN: "Marathi",
  bn: "Bengali",
  as: "Assamese",
  gu_IN: "Gujarati",
  gu: "Gujarati",
  pa: "Punjabi",
  or: "Oriya",
  ml: "Malayalam",
  kn: "Kannada",
  ta: "Tamil",
  te: "Telugu",
  si: "Sinhala",
  my: "Burmese",
  km: "Khmer",
  lo: "Lao",
  vi_VN: "Vietnamese",
  vi: "Vietnamese",
  id: "Indonesian",
  tl: "Tagalog",
  ms: "Malay",
  am: "Amharic",
  ti: "Tigrinya",
  om: "Oromo",
  so: "Somali",
  sw: "Swahili",
  rw: "Kinyarwanda",
  rn: "Rundi",
  ny: "Nyanja",
  mg: "Malagasy",
  eo: "Esperanto",
  cy: "Welsh",
  eu: "Basque",
  ca_ES: "Catalan",
  ca: "Catalan",
  la: "Latin",
  qu: "Quechua",
  gn: "Guarani",
  ay: "Aymara",
  tt: "Tatar",
  ug: "Uyghur",
  dz_BT: "Dzongkha",
  dz: "Dzongkha",
  jv: "Javanese",
  su: "Sundanese",
  gl: "Galician",
  af_ZA: "Afrikaans",
  af: "Afrikaans",
  br: "Breton",
  iu_CA: "Inuktitut",
  iu: "Inuktitut",
  gd: "Scottish Gaelic",
  gv: "Manx",
  to_TO: "Tongan",
  to: "Tongan",
  grc: "Ancient Greek",
  kl: "Kalaallisut",
  az: "Azerbaijani"
}

/*let languages = {
    en: "English (United States)",
    fr: "French (France)",
    de: "German (Germany)",
    it: "Italian (Italy)",
    nl: "Dutch (Netherlands)",
    sv: "Swedish (Sweden)",
    es: "Spanish (Spain)",
    da: "Danish (Denmark)",
    pt: "Portuguese (Brazil)",
    no: "Norwegian Bokmål (Norway)",
    nn: "Norwegian Nynorsk (Norway)",
    he: "Hebrew (Israel)",
    ja: "Japanese (Japan)",
    fi: "Finnish (Finland)",
    el: "Greek (Greece)",
    is: "Icelandic (Iceland)",
    mt: "Maltese (Malta)",
    tr: "Turkish (Turkey)",
    hr: "Croatian (Croatia)",
    "zh-Hans": "Chinese (China)",
    ur: "Urdu (Pakistan)",
    hi: "Hindi (India)",
    th: "Thai (Thailand)",
    ko: "Korean (South Korea)",
    lt: "Lithuanian (Lithuania)",
    pl: "Polish (Poland)",
    hu: "Hungarian (Hungary)",
    et: "Estonian (Estonia)",
    lv: "Latvian (Latvia)",
    fo: "Faroese (Faroe Islands)",
    fa: "Persian (Iran)",
    ru: "Russian (Russia)",
    ga: "Irish (Ireland)",
    ro: "Romanian (Romania)",
    cs: "Czech (Czech Republic)",
    sk: "Slovak (Slovakia)",
    sl: "Slovenian (Slovenia)",
    sr: "Serbian (Serbia)",
    mk: "Macedonian (Macedonia)",
    bg: "Bulgarian (Bulgaria)",
    uk: "Ukrainian (Ukraine)",
    be: "Belarusian (Belarus)",
    uz: "Uzbek (Uzbekistan)",
    hy: "Armenian (Armenia)",
    ka: "Georgian (Georgia)",
    en_US: "English (United States)",
    fr_FR: "French (France)",
    de_DE: "German (Germany)",
    it_IT: "Italian (Italy)",
    nl_NL: "Dutch (Netherlands)",
    sv_SE: "Swedish (Sweden)",
    es_ES: "Spanish (Spain)",
    da_DK: "Danish (Denmark)",
    pt_BR: "Portuguese (Brazil)",
    nb_NO: "Norwegian Bokmål (Norway)",
    nb: "Norwegian Bokmål (Norway)",
    nn_NO: "Norwegian Nynorsk (Norway)",
    he_IL: "Hebrew (Israel)",
    ja_JP: "Japanese (Japan)",
    fi_FI: "Finnish (Finland)",
    el_GR: "Greek (Greece)",
    is_IS: "Icelandic (Iceland)",
    mt_MT: "Maltese (Malta)",
    tr_TR: "Turkish (Turkey)",
    hr_HR: "Croatian (Croatia)",
    zh: "Chinese (China)",
    zh_CN: "Chinese (China)",
    ur_PK: "Urdu (Pakistan)",
    hi_IN: "Hindi (India)",
    th_TH: "Thai (Thailand)",
    ko_KR: "Korean (South Korea)",
    lt_LT: "Lithuanian (Lithuania)",
    pl_PL: "Polish (Poland)",
    hu_HU: "Hungarian (Hungary)",
    et_EE: "Estonian (Estonia)",
    lv_LV: "Latvian (Latvia)",
    fo_FO: "Faroese (Faroe Islands)",
    fa_IR: "Persian (Iran)",
    ru_RU: "Russian (Russia)",
    ga_IE: "Irish (Ireland)",
    ro_RO: "Romanian (Romania)",
    cs_CZ: "Czech (Czech Republic)",
    sk_SK: "Slovak (Slovakia)",
    sl_SI: "Slovenian (Slovenia)",
    sr_CS: "Serbian (Serbia)",
    mk_MK: "Macedonian (Macedonia)",
    bg_BG: "Bulgarian (Bulgaria)",
    uk_UA: "Ukrainian (Ukraine)",
    be_BY: "Belarusian (Belarus)",
    uz_UZ: "Uzbek (Uzbekistan)",
    hy_AM: "Armenian (Armenia)",
    ka_GE: "Georgian (Georgia)",
    en_GB: "English (United Kingdom)",
    en_AU: "English (Australia)",
    en_CA: "English (Canada)",
    en_SG: "English (Singapore)",
    en_IE: "English (Ireland)",
    it_CH: "Italian (Switzerland)",
    de_CH: "German (Switzerland)",
    de_AT: "German (Austria)",
    nl_BE: "Dutch (Belgium)",
    zh_TW: "Chinese (Taiwan)",
    fr_CA: "French (Canada)",
    fr_CH: "French (Switzerland)",
    fr_BE: "French (Belgium)",
    pt_PT: "Portuguese (Portugal)",
    ar: "Arabic",
    el_CY: "Greek (Cyprus)",
    ur_IN: "Urdu (India)",
    se: "Northern Sami",
    yi: "Yiddish",
    kk: "Kazakh",
    sq: "Albanian",
    mo: "Moldavian",
    ky: "Kyrgyz",
    tg: "Tajik",
    tk: "Turkmen",
    mn: "Mongolian",
    ps: "Pashto",
    ku: "Kurdish",
    ks: "Kashmiri",
    sd: "Sindhi",
    bo: "Tibetan",
    es_XL: "Spanish (Latin America)",
    ne_NP: "Nepali (Nepal)",
    ne: "Nepali (Nepal)",
    sa: "Sanskrit",
    mr: "Marathi (India)",
    mr_IN: "Marathi (India)",
    bn: "Bengali",
    as: "Assamese",
    gu_IN: "Gujarati (India)",
    gu: "Gujarati (India)",
    pa: "Punjabi",
    or: "Oriya",
    ml: "Malayalam",
    kn: "Kannada",
    ta: "Tamil",
    te: "Telugu",
    si: "Sinhala",
    my: "Burmese",
    km: "Khmer",
    lo: "Lao",
    vi_VN: "Vietnamese (Vietnam)",
    vi: "Vietnamese (Vietnam)",
    id: "Indonesian",
    tl: "Tagalog",
    ms: "Malay",
    am: "Amharic",
    ti: "Tigrinya",
    om: "Oromo",
    so: "Somali",
    sw: "Swahili",
    rw: "Kinyarwanda",
    rn: "Rundi",
    ny: "Nyanja",
    mg: "Malagasy",
    eo: "Esperanto",
    cy: "Welsh",
    eu: "Basque",
    ca_ES: "Catalan (Spain)",
    ca: "Catalan (Spain)",
    la: "Latin",
    qu: "Quechua",
    gn: "Guarani",
    ay: "Aymara",
    tt: "Tatar",
    ug: "Uyghur",
    dz_BT: "Dzongkha (Bhutan)",
    dz: "Dzongkha (Bhutan)",
    jv: "Javanese",
    su: "Sundanese",
    gl: "Galician",
    af_ZA: "Afrikaans (South Africa)",
    af: "Afrikaans (South Africa)",
    br: "Breton",
    iu_CA: "Inuktitut (Canada)",
    iu: "Inuktitut (Canada)",
    gd: "Scottish Gaelic",
    gv: "Manx",
    to_TO: "Tongan (Tonga)",
    to: "Tongan (Tonga)",
    grc: "Ancient Greek",
    kl: "Kalaallisut",
    az: "Azerbaijani"
};*/

module.exports = {
    languages
}
